((org-mode . (
               (com1 . "pandoc Klausur.md -t pdf -o Klausur.pdf && zathura Klausur.pdf")
               (com2 . "")
               (com3 . "")
               (com4 . "")
               (com5 . "")
               (com6 . "")
               (com7 . "")
               (com8 . "")
               (com9 . "")
               (com0 . "")
               (org-html-validation-link . nil)
               )))
